title: <%= name %>
description: <%= description %>

# add any site-wide meta tags here
meta:
  og:type: site

# this should *not* include the trailing slash
url: 

markdown: redcarpet
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - CONTRIBUTING.md
  - '.sass-cache'
  - '.ruby-version'
  - vendor
  - node_modules
